### ISSUE TITLE
Another similar project

### ISSUE THREAD

**Issue by noraj** [many-passwords/many-passwords#59]
Hi,

I'm sorry, I'm sure you won't be happy to read this.

There are already many project that are a collection of default credentials for all kind of applications, services, devices, etc.

Some of them:

- [Changeme](https://github.com/ztgrace/changeme "Changeme project")
- [Routersploit]( https://github.com/threat9/routersploit "Routersploit project")
- [betterdefaultpasslist]( https://github.com/govolution/betterdefaultpasslist "betterdefaultpasslist")
- [Seclists]( https://github.com/danielmiessler/SecLists/tree/master/Passwords/Default-Credentials "Seclist project")
- [ics-default-passwords](https://github.com/arnaudsoullie/ics-default-passwords)

But there is already a META-project called [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) that is merging and standardizing them all.

[DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) is maintained and updated, as also a directory of default SSH keys, include the default CSV with all credentials but also an automatically build JSON and README and has a basic shell command to search in it.

I also have personally developed a CLI tool named [pass-station](https://github.com/noraj/pass-station) to make more advanced search using this database.

So please do not open a similar concurrent project doing exactly the same thing and deviding open source community efforts, please contribute to [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) instead.

Thanks

**Comment by noraj** [comment]
Maybe you can re-use the source code of your website https://github.com/many-passwords/many-passwords.github.io to make a website for DefaultCreds-cheat-sheet  instead as it has no website yet.

**Comment by noraj** [comment]
The XKCD about this issue:

![](https://imgs.xkcd.com/comics/standards.png)

**Comment by noraj** [comment]
I already know part of the future answer, while you have 281 entries and 38 stars on your new project, DefaultCreds-cheat-sheet has 3349 entries and 1,8k stars. But your entries has a better quality including version, Access Type, Privileges and notes in addition to the default vendor and credentials. But the idea is the same I'd prefer see you help improve the quality of DefaultCreds-cheat-sheet by adding those additional info rather than starting a new fork and having spited efforts.

**Comment by piechowiakmichal** [comment]
Hi!

As you write yourself, there are many projects that serve the same purpose - collecting default credentials, passwords etc. 

You relate to the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project. As I understand correctly, you think he is the correct project, META-project.

As you well noticed he has got worse quality entries. My project has less entries because the entries are of better quality. In my case, quality goes hand in hand with quantity. This requires more time, so the project needs more time to develop. Even though, the project only contains 280 entries (note that at the time of writing this answer, the project has 3 unaccepted pull requests yet) he collected 38 stars (the number is increasing all the time).

[Many passwords](https://github.com/many-passwords) it also has a [website](https://many-passwords.github.io/) which is a big plus, it is updated automatically. The password file is automatically sorted, which makes it easier to find the password. Of course, there are things that are not there yet, but I have them in the plan. For example, automatic removal of duplicate entries.

> So please do not open a similar concurrent project doing exactly the same thing and deviding open source community efforts, please contribute to DefaultCreds-cheat-sheet instead.

I quote these words because I consider them the most serious accusation. You say that I shouldn't open a project that does the same and do divide open source community. Let's answer the question, who does it? [Many passwords](https://github.com/many-passwords) whether [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet)? The [Many passwords](https://github.com/many-passwords) project exists since Oct 13, 2020 and the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project exists since Jan 1, 2021. You emphasize in the last comment that my project is new, right, my project is less than a year old, but let's take a look at the project you praise. The [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project is younger, so you can say that this project started to divide the open source community. Not my project, not [Many passwords](https://github.com/many-passwords). The [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project only gathered 5 contributors. [Many passwords](https://github.com/many-passwords) gathered over 40 contributors. [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) collected more entries in less time, right, much more, but you have to admit that the quality is much worse. 

So which project should stop in favor of the other? Which project is the one that really devide the open source community?

Referring to XKCD, he has a lot of truth in him. Let's translate it into the two above-mentioned projects. We have two projects. One of them has fewer entries, but they are of better quality. The second one has more entries, but they are of poorer quality. Standardizing something. Should we discard something that develops slower because it needs more work? So do you think that the standard should be a project that develops faster because someone has overlooked the quality issues?

I believe that we should strive for better quality along with development. Quality should not be left aside because more time is needed then. It's not about doing anything fast. This should be done right - that is what the [Many passwords](https://github.com/many-passwords) project.

Thank you for taking your time, but as you have probably already deduced from my speech I will not take part in the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project. I'm counting on your contribution in [Many passwords](https://github.com/many-passwords) once you understand what should really be a priority.

Have a nice evening and day!

**Comment by noraj** [comment]
> As you write yourself, there are many projects that serve the same purpose - collecting default credentials, passwords etc.
> 
> You relate to the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project. As I understand correctly, you think he is the correct project, META-project.
> 
> As you well noticed he has got worse quality entries. My project has less entries because the entries are of better quality. In my case, quality goes hand in hand with quantity. This requires more time, so the project needs more time to develop. Even though, the project only contains 280 entries (note that at the time of writing this answer, the project has 3 unaccepted pull requests yet) he collected 38 stars (the number is increasing all the time).
> 
> [Many passwords](https://github.com/many-passwords) it also has a [website](https://many-passwords.github.io/) which is a big plus, it is updated automatically. The password file is automatically sorted, which makes it easier to find the password. Of course, there are things that are not there yet, but I have them in the plan. For example, automatic removal of duplicate entries.

My point was add the quality to the existing project and the website rather than creating a new one.



> I quote these words because I consider them the most serious accusation. You say that I shouldn't open a project that does the same and do divide open source community. Let's answer the question, who does it? [Many passwords](https://github.com/many-passwords) whether [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet)? The [Many passwords](https://github.com/many-passwords) project exists since Oct 13, 2020 and the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project exists since Jan 1, 2021. You emphasize in the last comment that my project is new, right, my project is less than a year old, but let's take a look at the project you praise. The [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project is younger, so you can say that this project started to divide the open source community. Not my project, not [Many passwords](https://github.com/many-passwords). The [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project only gathered 5 contributors. [Many passwords](https://github.com/many-passwords) gathered over 40 contributors. [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) collected more entries in less time, right, much more, but you have to admit that the quality is much worse.

I'm very sorry, I didn't saw your project was anterior, and wouldn't have crated this issue if I have seen so.
You are correct Many password was created on Oct 11, 2020 while DefaultCreds-cheat-sheet on Dec 27, 2020.
So please receive my excuses.

> I believe that we should strive for better quality along with development. Quality should not be left aside because more time is needed then. It's not about doing anything fast. This should be done right - that is what the [Many passwords](https://github.com/many-passwords) project.

I agree quality over quantity.

> Thank you for taking your time, but as you have probably already deduced from my speech I will not take part in the [DefaultCreds-cheat-sheet](https://github.com/ihebski/DefaultCreds-cheat-sheet) project. I'm counting on your contribution in [Many passwords](https://github.com/many-passwords) once you understand what should really be a priority.

Now I don't know if I should help many-passwords get more entries or DefaultCreds-cheat-sheet get more quality 🤔 

I'll probably help you import many entries but I'll need a lot of time to clean this out and enrich the data.

**Comment by piechowiakmichal** [comment]
I am glad that we can end our discussion in a nice way. I look forward to if you would like to contribute! All the best!

**Comment by noraj** [comment]
> I am glad that we can end our discussion in a nice way. I look forward to if you would like to contribute! All the best!

I'm already working on a first PR.
